apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubenews
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kubenews
  template:
    metadata:
      labels:
        app: kubenews
    spec:
      containers:
        - name: kubenews
          image: vinex11/kube-news:v1
          #resources:
            #limits:
            #  memory: "512Mi"
            #  cpu: "500m"
            #ports:
            #- containerPort: 8080
          env:
            - name: DB_PASSWORD
              value: "kubenews@123"
            - name: DB_USERNAME
              value: "kubenews"
            - name: DB_DATABASE
              value: "kubenews"
            - name: DB_HOST
              value: "service-postgre"     

---
apiVersion: v1
kind: Service
metadata:
  name: service-kubenews
spec:
  selector:
    app: kubenews
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30000
  type: NodePort
