apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgre
spec:
  #replicas: 2
  selector:
    matchLabels:
      app: postgre
  template:
    metadata:
      labels:
        app: postgre
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "5432"
        prometheus.io/path: "/metrics"

    spec:
      containers:
        - name: postgre
          image: postgres:14.3
          #resources:
            #limits:
            #  memory: "512Mi"
            #  cpu: "500m"
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              value: "kubenews@123"
            - name: POSTGRES_USER
              value: "kubenews"
            - name: POSTGRES_DB
              value: "kubenews"

---
apiVersion: v1
kind: Service
metadata:
  name: service-postgre
spec:
  selector:
    app: postgre
  ports:
  - port: 5432
    targetPort: 5432
      #nodePort: 30000
      #type: NodePort
